### ISSUE TITLE
Non si riesce ad aprire facilmente la console

### ISSUE THREAD

**Issue by mmirandola-igw** [Broly366/Rock-Paper-Scissors#1]
Ciao MoMo, se l'applicazione parte subito con un console.log la gente non riesce facilmente ad aprire la console (almeno su Chrome).
Dovresti a mio avviso creare un pulsante "Start" al centro della pagina che fa partire il gioco, così si ha tempo di aprire gli strumenti di sviluppo

**Comment by Broly366** [comment]
Ciao Michele, Grazie per il consiglio. Ho aggiunto UI quindi adesso il problema non si dovrebbe più ripresentare. Potresti darmi un Feedback e su possibili miglioramenti? Grazieee:)

**Comment by mmirandola-igw** [comment]
Ciao, ho visto il lavoro che hai fatto per la parte UI e direi che è un ottimo lavoro e risolve il problema.
Considero l'issue ufficialmente chiusa :-)
